import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const CONTEXT_URL = "https://schema.org/docs/jsonldcontext.json";
const OUTPUT_PATH = resolve(process.cwd(), "schema-vocabulary.generated.ts");

type JsonLdContext = {
  "@context": Record<string, unknown>;
};

const isSchemaOrgId = (id: string): boolean => {
  return (
    id.startsWith("schema:") ||
    id.startsWith("http://schema.org/") ||
    id.startsWith("https://schema.org/")
  );
};

const extractId = (def: unknown): string | undefined => {
  if (typeof def === "string") return def;
  if (def && typeof def === "object") {
    const maybe = (def as { "@id"?: unknown })["@id"];
    if (typeof maybe === "string") return maybe;
  }
  return undefined;
};

const escapeTemplateLiteral = (s: string): string =>
  s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const run = async (): Promise<void> => {
  const res = await fetch(CONTEXT_URL);
  if (!res.ok) {
    throw new Error(
      `Failed to fetch ${CONTEXT_URL}: ${res.status} ${res.statusText}`,
    );
  }
  const json = (await res.json()) as JsonLdContext;
  const ctx = json?.["@context"];
  if (!ctx || typeof ctx !== "object") {
    throw new Error("Invalid jsonldcontext.json: missing @context object");
  }

  const terms: string[] = [];
  for (const [term, def] of Object.entries(ctx)) {
    if (term.startsWith("@")) continue;
    const id = extractId(def);
    if (!id) continue;
    if (id.startsWith("@")) continue; // JSON-LD keyword alias (e.g. { id: '@id' })
    if (!isSchemaOrgId(id)) continue;
    terms.push(term);
  }

  const uniqueSorted = [...new Set(terms)].sort((a, b) => a.localeCompare(b));

  // Note: jsonldcontext.json contains Schema.org terms (types + properties). We export the same
  // allowlist for both knownTypes and knownProperties to stay aligned with validator.schema.org's
  // permissive vocabulary acceptance.
  const content = `// This file is generated by scripts/build-vocabulary.ts
// Source: ${escapeTemplateLiteral(CONTEXT_URL)}
// DO NOT EDIT MANUALLY.

export const schemaVocabularySource = ${JSON.stringify(CONTEXT_URL)} as const;

export const knownTermsArray = ${JSON.stringify(uniqueSorted, null, 2)} as const;

export const knownTypesArray = knownTermsArray;
export const knownPropertiesArray = knownTermsArray;

export const knownTypes = new Set<string>(knownTypesArray);
export const knownProperties = new Set<string>(knownPropertiesArray);
`;

  writeFileSync(OUTPUT_PATH, content, "utf-8");
  // eslint-disable-next-line no-console
  console.log(
    `Wrote ${uniqueSorted.length} Schema.org terms to ${OUTPUT_PATH}`,
  );
};

run().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
